# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'
platform :ios, '11.0'

pod 'SVProgressHUD'
pod 'MJExtension'
pod 'MJRefresh' ,"3.7.2" 
pod 'Masonry'
pod 'SDCycleScrollView'
pod 'FMDB'
pod 'ZYCornerRadius'
pod 'SDWebImage' ,"3.8.2"
pod 'ZXingObjC'
pod 'TZImagePickerController'
pod 'IQKeyboardManager'
pod 'AFNetworking'
pod 'CDDPagerController'

flutter_application_path = '../my_flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'CDDStoreDemo' do
  install_all_flutter_pods(flutter_application_path)
end

post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
end
